<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Allie Cobranza Especializada</title>
<style> 
    p {
        text-align: justify-all;
    }
    
</style>
</head>

<body>



<!-- ContainerStarts -->
<div style="width:1024px; margin-left:auto; margin-right:auto;">
   
        
        <!-- SliderEnds -->
        <!-- Text Starts-->
        <div style="background-image:url(img/textbackaviso.jpg); width:1000px; height:2160px; margin-top: -5px;">
        	
            <div style="margin-top: 8px; margin-left: 70px; width:870px;">
            	<img src="img/lineanosotros.jpg" width="847" height="6">
                <br>
                <p><strong>Allie Alianzas Estrátegicas, S.A.P.I de C.V.</strong> (en lo sucesivo ALLIE) con domicilio en: Avenida del Parque No. 11, Colonia San Ángel, Delegación Alvaro Obregón, México, D.F., C.P. 01040 ; en cumplimiento a lo dispuesto por la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, es el responsable del uso y protección de los datos personales que usted EL CLIENTE, le proporcione. Y al respecto le informamos lo siguiente:</p>
                <p><strong>FINALIDAD DEL TRATAMIENTO DE DATOS PERSONALES.</strong><br/>ALLIE, Recaba y utiliza los datos personales que reciba de sus clientes con la finalidad de: A) Identificarlos. B) Llevar a cabo gestiones de cobro de adeudos de créditos de cualquier tipo. C) Informarle sobre el estatus de dicho crédito, así como las obligaciones contraídas y que derivan de dicha obligación incumplida. D) Realizar requerimientos legales de pago. E) Ceder o enajenar los derechos que a su favor se deriven de los contratos que se hubieren celebrado. F) Otorgarles información relacionada con los adeudos que se requieren de pago. G) Ofrecerles los diferentes productos y/o servicios que ponemos a su disposición, así como cualquier cambio que se realice en estos según sea el caso, y H) Para fines mercadotécnicos, publicitarios y de evaluación en la calidad de los servicios que ofrece ALLIE.</p>
                <p>De esta manera se informa a los clientes, que las finalidades que dieron origen a la existencia de la relación jurídica, así como aquellas que son necesarias para el servicio que solicita, son las enunciadas en los incisos A), B), C), D) y E) del párrafo que antecede. De manera adicional, utilizaremos su información personal para las finalidades enunciadas anteriormente en los incisos F), G) y H), acciones que si bien es cierto no son necesarias para el servicio que solicita, estas nos permiten brindarle una mejor atención y servicio. Sin embargo, ALLIE garantiza el derecho de sus clientes a manifestar su negativa para el tratamiento de sus datos personales, por ello en caso de que EL CLIENTE no desee que sus datos personales sean tratados para estos fines adicionales, podrá informar a ALLIE, su negativa desde el momento en que esta última ponga a su disposición el presente Aviso de Privacidad. La negativa para el uso de sus datos personales para estas finalidades no podrá ser un motivo para que ALLIE le niegue los servicios y productos que EL CLIENTE solicita o contrate con nosotros. Entendiéndose así, que con la firma autógrafa de EL CLIENTE, este último expresa su conformidad para que ALLIE pueda hacer uso de sus datos personales. Sin perjuicio de su derecho para revocar el consentimiento que previamente hubiere otorgado, o bien para ejercer su derecho a oponerse al tratamiento de sus datos personales en términos de las disposiciones aplicables, derechos que en todo momento serán garantizados por ALLIE.</p>
                <p><strong>OBTENCIÓN Y TRATAMIENTO DE LOS DATOS PERSONALES.</strong><br/>ALLIE, recaba los datos de sus Clientes a) de manera personal, o b) por cualquier otro medio, siempre y cuando esté permitido por la Ley. Los datos que ALLIE recaba de sus Clientes son tratados a través de medios técnicos, administrativos y digitales adecuados que permiten proteger su información. Los datos de los Clientes de ALLIE reciben un tratamiento secreto y confidencial por parte de ALLIE, quien adopta para tal efecto las medidas necesarias para evitar su alteración, pérdida, tratamiento o acceso no autorizado. Por su parte, el Cliente declara que sus datos son exactos, auténticos, fidedignos y completos; y son responsabilidad del Cliente que los proporciona, por lo que se libera a ALLIE de cualquier responsabilidad relacionada al respecto. Los datos que los Clientes libre y voluntariamente proporcionan a ALLIE, pueden incluir: datos de identificación, laborales, patrimoniales, así como referencias personales del Cliente.</p>
                <p><strong>EJERCICIO DE LOS DERECHOS DE ACCESO, RECTIFICACIÓN, CANCELACIÓN U OPOSICIÓN (DERECHOS ARCO).</strong><br/>Los Clientes serán responsables de la exactitud, veracidad, autenticidad y vigencia de sus datos. Los Clientes de ALLIE tienen el derecho de 1) ACCESO, acceder a los datos personales que les fueron recabados, 2) RECTIFICACIÓN, a rectificar sus datos, en caso de ser estos inexactos, incompletos o desactualizados, 3) CANCELACION, a cancelar sus datos cuando considere que la misma no está siendo utilizada conforme a los principios, deberes y obligaciones previstas en la normativa, 4) OPOSICIÓN, a oponerse al tratamiento de dichos datos, en términos de la Ley y las disposiciones aplicables en la materia. Estos derechos se conocen como derechos ARCO.</p>
                <p><strong>REVOCACIÓN DEL CONSENTIMIENTO.</strong><br/>
En cualquier momento EL CLIENTE podrá informar a ALLIE su determinación de revocar el consentimiento que previamente se hubiere otorgado para el tratamiento de los datos personales de acuerdo con las finalidades descritas en el Aviso de Privacidad, a fin de que ALLIE deje de hacer uso de los mismos y siempre y cuando el consentimiento que se pretenda revocar no derive de una relación jurídica contractual u operación pactada con ALLIE, que la ley lo permita o que así se hubiere pactado expresamente entre ALLIE y EL CLIENTE. Sin embargo, es importante que tenga en cuenta que no en todos los casos podremos concluir el uso de forma inmediata, ya que es posible que por alguna obligación legal requerimos seguir tratando sus datos personales. Los medios y el procedimiento para hacerlo efectivo se mencionan a continuación.</p>
				<p><strong>MEDIOS Y PROCEDIMIENTO PARA EL EJERCICIO DE LOS DERECHOS ARCO Y PARA LA REVOCACIÓN DEL CONSENTIMIENTO.</strong><br/>Los Clientes de ALLIE podrán ejercer sus derechos ARCO y revocar su consentimiento para el tratamiento de sus datos personales a través de la solicitud respectiva, solicitud que podrá ser obtenida en forma gratuita en cualquiera de las sucursales de ALLIE y deberá ser entregada a un Administrador de Sucursal. Dicha solicitud indicará los requisitos y el procedimiento para el ejercicio de los derechos ARCO y/o para la revocación del consentimiento para el tratamiento de sus datos personales, que a continuación se describe: Recibida la solicitud por el Administrador de Sucursal de ALLIE, debidamente requisitada y una vez que se acredite la identidad del Cliente (titular de los datos personales), se entregará un acuse de recibo al cliente. A partir de la fecha en que sea recibida la solicitud, ALLIE dará respuesta por escrito a la misma en un término no mayor a 10 (diez) días hábiles. La respuesta se pondrá a disposición del Cliente en la sucursal de ALLIE donde se hubiere presentado la solicitud, dentro del plazo antes señalado. En caso de resultar procedente, ALLIE cumplirá con lo solicitado dentro de los 10 (diez) días hábiles posteriores. Para mayor información sobre el procedimiento o requisitos para el uso y revocación del uso de sus datos personales, ponemos a su disposición los datos de contacto de Nuestra Dirección de Protección de Datos Personales, teléfono (0155) 5663 4350, de lunes a viernes de 10:00 hrs. a 18:00 hrs, email gerardo.mandujano@allie.mx sitio de internet allie.mx</p>
                <p><strong>LIMITACIÓN DEL USO O DIVULGACIÓN DE SUS DATOS PERSONALES.</strong><br/>Si desea dejar de recibir publicidad o promociones de nuestros productos y servicios financieros, puede solicitar su inscripción al Registro Público de Usuarios (REUS) a la Comisión Nacional para la Protección y Defensa de los Usuarios de Servicios Financieros (CONDUSEF); o bien, solicitar su registro en los listados internos en cualquiera de nuestras sucursales.</p>
                <p><strong>USO DE COOKIES O WEB BEACONS U OTRAS TECNOLOGIAS SIMILARES.</strong><br/>Las Cookies son archivos de texto que son descargados automáticamente y almacenados en el disco duro del equipo de cómputo del usuario al navegar en una página de internet específica, que permiten recordar al servidor de internet algunos datos sobre este usuario, entre ellas sus preferencias para la visualización de las páginas en ese servidor, nombre y contraseña. Por su parte, las Web Beacons son imágenes insertadas en una página de internet o correo electrónico, que puede ser utilizado para monitorear el comportamiento de un visitante, como almacenar información sobre la dirección IP del usuario, duración del tiempo de interacción en dicha página y el tipo de navegador utilizado. Le informamos que no utilizamos Cookies y Web Beacons para obtener información personal de EL CLIENTE.</p>
                <p><strong>TRANSFERENCIA DE DATOS PERSONALES POR ALLIE.</strong><br/>ALLIE utiliza los datos personales de sus Clientes exclusivamente para los fines señalados en el presente Aviso de Privacidad y los conserva por el tiempo permitido por disposición de ley. ALLIE únicamente comparte y/o transfiere los datos personales de sus Clientes con terceros. 1) Cuando así corresponda, cedamos y/o enajenemos la cartera de crédito. 2) Cuando corresponda hacer requerimientos de pago a través de despachos de cobranza externos, 3) Cuando ALLIE otorgue en garantía los derechos que a su favor se deriven de los contratos celebrados, 4) Para consulta y verificación de los datos e información otorgada por el Cliente, 5) Cuando así se requiera por disposición legal o por orden de autoridad competente debidamente fundada y motivada, y 6) En los supuestos señalados en el artículo 37 de la Ley. Fuera de los casos enunciados, usted tiene la confianza de que sus datos no serán transferidos a terceras personas sin su expreso consentimiento.</p>
                <p>En todo caso, ALLIE garantiza que las finalidades del tratamiento de los datos personales del Cliente serán respetadas por los terceros receptores cuando se verifique alguna de las transferencias antes enunciadas. Los terceros receptores de los datos personales de los Clientes podrán ser despachos de cobranza, autoridades gubernamentales competentes para solicitar dicha información. Las finalidades de las transferencias antes enunciadas perseguirán 1) El cumplimiento de la obligación impuesta o requerida por autoridad competente. 2) El mantenimiento y/o cumplimiento de las obligaciones y derechos contraídos por medio de los contratos celebrados con los clientes. 3) La Protección de los derechos de pago de ALLIE. 4) La garantía de cualquier derecho derivado de los contratos que celebre ALLIE. 5) Publicidad y Promoción de los productos financieros que ALLIE ofrezca a sus Clientes. En este acto, el Cliente manifiesta su conformidad para que ALLIE pueda llevar a cabo las transferencias en los supuestos antes enunciados, a los terceros receptores antes mencionados y por las finalidades enunciadas, por lo que firma de enterado y de conformidad el presente Aviso de Privacidad.</p>
                <p><strong>COMUNICACIÓN.</strong> El presente Aviso de Privacidad puede sufrir modificaciones, cambios, o actualizaciones derivadas de nuevos requerimientos legales; de nuestras propias necesidades por los productos o servicios que ofrecemos; de nuestras prácticas de privacidad; de cambios en nuestro modelo de negocio, o por otras causas. Cualquier cambio y/o modificación total o parcial al presente Aviso de Privacidad, la haremos de su conocimiento, a través de nuestro sitio de internet así como en cualquiera de nuestras sucursales a su disposición.</p>
                <p>Si usted considera que su derecho de protección de datos personales ha sido vulnerado por alguna conducta nuestra o de nuestros empleados puede contactar a nuestra Dirección de Protección de Datos Personales, teléfono (0155) 5663 4350, de lunes a viernes de 10:00 hrs. a 18:00 hrs., email <a href="mailto:gerardo.mandujano@allie.mx">gerardo.mandujano@allie.mx</a> sitio de internet allie.mx Lo anterior, sin perjuicio de su derecho de acudir ante el Instituto Nacional de Transparencia, Acceso a la Información y Protección de Datos Personales (INAI).</p>
                
            </div> 
            
            
              
  </div>
 		<!-- Text Ends-->      
  </div>
    <!-- Porque Ends -->
    
     <!-- Footer Starts -->    
	<div style="background-image:url(img/footerback.jpg); width:1000px; height:38px;">
	  <div style="color:black; font-size:11px; padding-top:8px; padding-left:40px; float:left;">
                	Derechos Reservados Alie Allianzas Estratégicas, S.A.P.I. de C.V.
                </div>
                <div style="color:#fff; font-size:12px; margin-top: -15px; padding-left:400px; float:left;">
               		<a href="index.php">Inicio</a>&nbsp;&nbsp;<a href="index.php?action=nosotros">Nosotros</a>&nbsp;&nbsp;<a href="index.php?action=contactanos">Contacto </a> 
                        <!--<a href="inicio.html">Inicio</a>&nbsp;&nbsp;<a href="nosotros.html">Nosotros</a>&nbsp;&nbsp;<a href="administracionycobranza.html">Administración y Cobranza</a> &nbsp;&nbsp;<a href="recuperacion.html">Recuperación de Cartera</a> &nbsp;&nbsp;<a href="ventadebienesadjudicados.html">Venta de Bienes Adjudicados</a> &nbsp;&nbsp;<a href="contacto.html">Contacto </a>--> 
                </div>
    </div>   
    <!-- Footer Ends -->  
</div>
<!-- ContainerEnds -->


</body>
</html>
